/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/widgets/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        aliceblue: "#ddf5ff",
        dodgerblue: "#0071ce",
        coral: "#ff8541",
        coralPink: "#FF8541",
        dark_green: "#208837",
        Vivid_Tangelo: "#FF8541",
        denim_Blue: "#156BA9",
        oceanEmerald: "#0FA90C",
        boulder: "#747474",
        silver: "#DEDEDE",
        darkGray: "#808080",
        dustyBlue: "#B0BFD6",
        azureDream: "#F2F8FF",
        indigo: "#332C60",
        stoneGray: "#C3C3C3",
        bone: "#F1F1F1",
        lightPink: "#F6F0FF",
        indigoLight: "#422C60",
        gold: "#fcd966",
        lightGreen: "#87DB85",
        tomatoRed: "#FF4141",
        orangeRed: "#FF6141",
        coralRed: "#FF8041",
        Lilac: "#CBC7E5",
        aquaMarine: "#94F098",
        lightGray: "#F2F2F2",
        choclate: "#682500",
        carretRed: "#F79761",
        eggShell: "#FFEFE5",
        darkClove: "#604F45",
        dark_Tangelo: "#D96E30",
        grey_light: "#EDEDED",
        burnt_sienna: "#A3410A",
        dark_taupe: "#4C392E",
        chocolate_brown: "#422F24",
        creamy_peach: "#FFF9F5",
        peachy_ivory: "#FFF3ED",
        lightishGreen: "#F3FFF6",
        darkerGreen: "#579035",
        lightishRed: "#FFF3F3",
        darkerdRed: "#F64141",
        lightishGray: "#F8F8F8",
        darkerGray: "#8B8E89",
        lightishYellow: "#FFFFED",
        darkerYellow: "#FFFF6E",
        customTextGray: "#747474",
        customBorderGray: "#DCDCDC",
        customLightOrange: "#FFEDE3",
        orange_red: "#FFEFE5",
        greige: "#EDEDEDCC",
        mithril: "#878787",
        charcoal: "#545454",
        almostBlack: "#2B2B2B",
        cantaloupe: "#FF8F5F",
        ivory: "#FFF5F0",
        iceBlue: "#D8EFFF",
        creamyPink: "#FFECEC",
        mistBlue: "#EFFFEB",
        coolGrey: "#787878",
        platinum: "#C1C1C1",
        classicSliver: "#BCBCBC",
        ironSky: "#818181",
        ironInk: "#818181",
        roseBrown: "#B5455E",
        subtleSilver: "#868686",
        platinumGray: "#797979",
        davys_Grey: "#555555",
        shadyGray: "#B7B7B7",
        silverChalice: "#ACACAC",
      },
      fontFamily: {
        "open-sans": "'Open Sans'",
      },
      fontSize: {
        inherit: "inherit",
      },
      borderWidth: {
        1: "1px",
      },
    },
  },
  plugins: [],
};
